steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/dataanalytics-347914/python-apps/xgboost_coupon_model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/dataanalytics-347914/python-apps/xgboost_coupon_model']

- name: 'us-central1-docker.pkg.dev/dataanalytics-347914/python-apps/xgboost_coupon_model'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python main.py & python -m pytest
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'xgboost-coupon-model'
   - '--image'
   - 'us-central1-docker.pkg.dev/dataanalytics-347914/python-apps/xgboost_coupon_model'
   - '--region'
   - 'us-central1'
   - '--allow-unauthenticated'
images:
- 'us-central1-docker.pkg.dev/dataanalytics-347914/python-apps/xgboost_coupon_model'

options:
  logging: CLOUD_LOGGING_ONLY